name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compilar proyecto
        run: python3 -m py_compile src/app.py

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar tests
        run: python3 src/app.py | grep "Hello CI/CD World!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Desplegar aplicación
      - run: ./scripts/deploy.sh
      - name: Guardar artifact
        uses: actions/upload-artifact@v3
        whit:
          name: deploy-files
          path: deploy/